## Practice Exercise

### About the Data set (Wine Quality.csv)
Attribute Information:

The dataset are related to red and white variants of the "Vinho Verde" wine. Vinho verde is a unique product from the Minho (northwest) region of Portugal. Medium in alcohol, is it particularly appreciated due to its freshness (specially in the summer). 

    1 - fixed acidity 
    2 - volatile acidity 
    3 - citric acid 
    4 - residual sugar 
    5 - chlorides 
    6 - free sulfur dioxide 
    7 - total sulfur dioxide 
    8 - density 
    9 - pH 
    10 - sulphates 
    11 - alcohol Output variable (based on sensory data): 
    12 - quality (score between 0 and 10)

## 1. Load the libraries:

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')

## 2. Importing the dataset:

In [3]:
wine_data = pd.read_csv('Wine_data.csv')
wine_data.head(5)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [4]:
wine_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         4898 non-null   float64
 1   volatile acidity      4898 non-null   float64
 2   citric acid           4898 non-null   float64
 3   residual sugar        4898 non-null   float64
 4   chlorides             4898 non-null   float64
 5   free sulfur dioxide   4898 non-null   float64
 6   total sulfur dioxide  4898 non-null   float64
 7   density               4898 non-null   float64
 8   pH                    4898 non-null   float64
 9   sulphates             4898 non-null   float64
 10  alcohol               4898 non-null   float64
 11  quality               4898 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 459.2 KB

## 3.EDA Descriptive Statistics:

### 3.1.  Measures of Central Tendency

Measures of Central Tendency define significant, representative and adequate values for a set of data, depending on what you want to analyze. They are the 

1. mean
2. median
3. quantiles and mode.

### 3.2 Check the  mean ,Mode, Median and Quantile for dataset?

### Mean

In [5]:
wine_data.mean()

fixed acidity             6.854788
volatile acidity          0.278241
citric acid               0.334192
residual sugar            6.391415
chlorides                 0.045772
free sulfur dioxide      35.308085
total sulfur dioxide    138.360657
density                   0.994027
pH                        3.188267
sulphates                 0.489847
alcohol                  10.514267
quality                   5.877909
dtype: float64

### Mode

In [6]:
wine_data.mode()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,6.8,0.28,0.3,1.2,0.044,29.0,111.0,0.992,3.14,0.5,9.4,6

### Median and Quantile

In [7]:
wine_data.median()

fixed acidity             6.80000
volatile acidity          0.26000
citric acid               0.32000
residual sugar            5.20000
chlorides                 0.04300
free sulfur dioxide      34.00000
total sulfur dioxide    134.00000
density                   0.99374
pH                        3.18000
sulphates                 0.47000
alcohol                  10.40000
quality                   6.00000
dtype: float64

### 3.3 check (Quantile 25%,50%,75%) for dataset

### Quantile 25%

In [8]:
wine_data.quantile(q=0.25)

fixed acidity             6.300000
volatile acidity          0.210000
citric acid               0.270000
residual sugar            1.700000
chlorides                 0.036000
free sulfur dioxide      23.000000
total sulfur dioxide    108.000000
density                   0.991723
pH                        3.090000
sulphates                 0.410000
alcohol                   9.500000
quality                   5.000000
Name: 0.25, dtype: float64


### Quantile 50%

In [9]:
wine_data.quantile(q=0.50)

fixed acidity             6.80000
volatile acidity          0.26000
citric acid               0.32000
residual sugar            5.20000
chlorides                 0.04300
free sulfur dioxide      34.00000
total sulfur dioxide    134.00000
density                   0.99374
pH                        3.18000
sulphates                 0.47000
alcohol                  10.40000
quality                   6.00000
Name: 0.5, dtype: float64

### Quantile 75%

In [10]:
wine_data.quantile(q=0.75)

fixed acidity             7.3000
volatile acidity          0.3200
citric acid               0.3900
residual sugar            9.9000
chlorides                 0.0500
free sulfur dioxide      46.0000
total sulfur dioxide    167.0000
density                   0.9961
pH                        3.2800
sulphates                 0.5500
alcohol                  11.4000
quality                   6.0000
Name: 0.75, dtype: float64

## 4. Measures of Dispersion

Measures of Dispersion are measures that indicate how spread the data is, or how they vary. The measures of dispersion are range, variance, standard deviation and the absolute deviation, or mean absolute deviation.

### 4.1 check the Range,Variance,Standard Deviation,Absolute Deviation or Mean Absolute Deviation?

### Range

In [11]:
##Range is maximum - min or that particular col.
wine_data.max() - wine_data.min() #Range Max - Min

fixed acidity            10.40000
volatile acidity          1.02000
citric acid               1.66000
residual sugar           65.20000
chlorides                 0.33700
free sulfur dioxide     287.00000
total sulfur dioxide    431.00000
density                   0.05187
pH                        1.10000
sulphates                 0.86000
alcohol                   6.20000
quality                   6.00000
dtype: float64

In [12]:
#Max Fixed acidity 
wine_data['fixed acidity'].max()

14.2

In [13]:
wine_data['fixed acidity'].min()

3.8

### Variance

In [14]:
wine_data.var()

fixed acidity              0.712114
volatile acidity           0.010160
citric acid                0.014646
residual sugar            25.725770
chlorides                  0.000477
free sulfur dioxide      289.242720
total sulfur dioxide    1806.085491
density                    0.000009
pH                         0.022801
sulphates                  0.013025
alcohol                    1.514427
quality                    0.784356
dtype: float64

### Standard Deviation

In [15]:
wine_data.std()

fixed acidity            0.843868
volatile acidity         0.100795
citric acid              0.121020
residual sugar           5.072058
chlorides                0.021848
free sulfur dioxide     17.007137
total sulfur dioxide    42.498065
density                  0.002991
pH                       0.151001
sulphates                0.114126
alcohol                  1.230621
quality                  0.885639
dtype: float64

### Absolute Deviation or Mean Absolute Deviation

In [17]:
wine_data.mad()

fixed acidity            0.644923
volatile acidity         0.073803
citric acid              0.086411
residual sugar           4.227788
chlorides                0.011462
free sulfur dioxide     13.149156
total sulfur dioxide    34.282442
density                  0.002447
pH                       0.118204
sulphates                0.087504
alcohol                  1.034213
quality                  0.670793
dtype: float64

## 5. Covariance and Correlation

1. Covariance is a numerical measure that indicates the inter-dependency between two variables. 
2. Covariance indicates how two variables behave together in relation to their averages. 
3. A covariance of 0 indicates that the variables are totally independant, while a high and positive covariance value means that a variable is big when the other is big. Analogously, a negative covariance with a high absolute value means that one variable is big when the other is small.
4. Covariance can be calculated through the cov() function.

### 5.1 Check the Covariance and Correlation scores . write your Observations?

### Covariance

In [18]:
wine_data.cov()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
fixed acidity,0.712114,-0.001931,0.029533,0.381022,0.000426,-0.708919,3.266013,0.000670,-0.054265,-0.001651,-0.125533,-0.084947
volatile acidity,-0.001931,0.010160,-0.001823,0.032865,0.000155,-0.166300,0.382354,0.000008,-0.000486,-0.000411,0.008400,-0.017382
citric acid,0.029533,-0.001823,0.014646,0.057829,0.000302,0.193630,0.622989,0.000054,-0.002992,0.000861,-0.011278,-0.000987
residual sugar,0.381022,0.032865,0.057829,25.725770,0.009828,25.800578,86.531303,0.012727,-0.148684,-0.015435,-2.812740,-0.438316
chlorides,0.000426,0.000155,0.000302,0.009828,0.000477,0.037674,0.184687,0.000017,-0.000298,0.000042,-0.009684,-0.004062
free sulfur dioxide,-0.708919,-0.166300,0.193630,25.800578,0.037674,289.242720,444.865891,0.014966,-0.001587,0.114938,-5.234509,0.122878
total sulfur dioxide,3.266013,0.382354,0.622989,86.531303,0.184687,444.865891,1806.085491,0.067352,0.014894,0.652645,-23.476605,-6.576746
density,0.000670,0.000008,0.000054,0.012727,0.000017,0.014966,0.067352,0.000009,-0.000042,0.000025,-0.002871,-0.000814
pH,-0.054265,-0.000486,-0.002992,-0.148684,-0.000298,-0.001587,0.014894,-0.000042,0.022801,0.002688,0.022565,0.013297
sulphates,-0.001651,-0.000411,0.000861,-0.015435,0.000042,0.114938,0.652645,0.000025,0.002688,0.013025,-0.002448,0.005425
alcohol,-0.125533,0.008400,-0.011278,-2.812740,-0.009684,-5.234509,-23.476605,-0.002871,0.022565,-0.002448,1.514427,0.474726
quality,-0.084947,-0.017382,-0.000987,-0.438316,-0.004062,0.122878,-6.576746,-0.000814,0.013297,0.005425,0.474726,0.784356

### Observation:

### Correlation

In [19]:
wine_data.corr()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
fixed acidity,1.000000,-0.022697,0.289181,0.089021,0.023086,-0.049396,0.091070,0.265331,-0.425858,-0.017143,-0.120881,-0.113663
volatile acidity,-0.022697,1.000000,-0.149472,0.064286,0.070512,-0.097012,0.089261,0.027114,-0.031915,-0.035728,0.067718,-0.194723
citric acid,0.289181,-0.149472,1.000000,0.094212,0.114364,0.094077,0.121131,0.149503,-0.163748,0.062331,-0.075729,-0.009209
residual sugar,0.089021,0.064286,0.094212,1.000000,0.088685,0.299098,0.401439,0.838966,-0.194133,-0.026664,-0.450631,-0.097577
chlorides,0.023086,0.070512,0.114364,0.088685,1.000000,0.101392,0.198910,0.257211,-0.090439,0.016763,-0.360189,-0.209934
free sulfur dioxide,-0.049396,-0.097012,0.094077,0.299098,0.101392,1.000000,0.615501,0.294210,-0.000618,0.059217,-0.250104,0.008158
total sulfur dioxide,0.091070,0.089261,0.121131,0.401439,0.198910,0.615501,1.000000,0.529881,0.002321,0.134562,-0.448892,-0.174737
density,0.265331,0.027114,0.149503,0.838966,0.257211,0.294210,0.529881,1.000000,-0.093591,0.074493,-0.780138,-0.307123
pH,-0.425858,-0.031915,-0.163748,-0.194133,-0.090439,-0.000618,0.002321,-0.093591,1.000000,0.155951,0.121432,0.099427
sulphates,-0.017143,-0.035728,0.062331,-0.026664,0.016763,0.059217,0.134562,0.074493,0.155951,1.000000,-0.017433,0.053678
alcohol,-0.120881,0.067718,-0.075729,-0.450631,-0.360189,-0.250104,-0.448892,-0.780138,0.121432,-0.017433,1.000000,0.435575
quality,-0.113663,-0.194723,-0.009209,-0.097577,-0.209934,0.008158,-0.174737,-0.307123,0.099427,0.053678,0.435575,1.000000

### Observation:

### 6.1 Check the statistcal summary or 5-point summary of data

In [20]:
wine_data.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000
mean,6.854788,0.278241,0.334192,6.391415,0.045772,35.308085,138.360657,0.994027,3.188267,0.489847,10.514267,5.877909
std,0.843868,0.100795,0.121020,5.072058,0.021848,17.007137,42.498065,0.002991,0.151001,0.114126,1.230621,0.885639
min,3.800000,0.080000,0.000000,0.600000,0.009000,2.000000,9.000000,0.987110,2.720000,0.220000,8.000000,3.000000
25%,6.300000,0.210000,0.270000,1.700000,0.036000,23.000000,108.000000,0.991723,3.090000,0.410000,9.500000,5.000000
50%,6.800000,0.260000,0.320000,5.200000,0.043000,34.000000,134.000000,0.993740,3.180000,0.470000,10.400000,6.000000
75%,7.300000,0.320000,0.390000,9.900000,0.050000,46.000000,167.000000,0.996100,3.280000,0.550000,11.400000,6.000000
max,14.200000,1.100000,1.660000,65.800000,0.346000,289.000000,440.000000,1.038980,3.820000,1.080000,14.200000,9.000000

### 6.2 Extract all the numeric_features from the dataset

In [30]:
num_fea = wine_data.select_dtypes(include=["int64","float64"])
num_fea.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

### 6.3 Determine the skewness of all the numerical features in the dataset

In [44]:
skewed_features = num_fea.apply(lambda x : skew(x.dropna())).sort_values(ascending=False)
skewed_features

NameError: name 'skew' is not defined

### 6.4 Find out which variables are highly skewned (skewness > 0.7)?

In [45]:
skewness=skewed_features[abs(skewed_features)>0.7]
skewness

NameError: name 'skewed_features' is not defined

In [52]:
slump_data = pd.read_csv('Slump+Test.csv')
slump_data.head(5)

   Cement   Slag  Fly ash  Water    SP  Coarse   Fine  SLUMP  FLOW  Strength
0   273.0   82.0    105.0  210.0   9.0   904.0  680.0   23.0  62.0     34.99
1   163.0  149.0    191.0  180.0  12.0   843.0  746.0    0.0  20.0     41.14
2   162.0  148.0    191.0  179.0  16.0   840.0  743.0    1.0  20.0     41.81
3   162.0  148.0    190.0  179.0  19.0   838.0  741.0    3.0  21.5     42.08
4   154.0  112.0    144.0  220.0  10.0   923.0  658.0   20.0  64.0     26.82

In [56]:
slump_data.mean()

Cement      229.894175
Slag         77.973786
Fly ash     149.014563
Water       197.167961
SP            8.539806
Coarse      883.978641
Fine        739.604854
SLUMP        18.048544
FLOW         49.610680
Strength     36.039417
dtype: float64

In [57]:
slump_data.median()

Cement      248.00
Slag        100.00
Fly ash     164.00
Water       196.00
SP            8.00
Coarse      879.00
Fine        742.70
SLUMP        21.50
FLOW         54.00
Strength     35.52
dtype: float64

In [58]:
slump_data.mode()

    Cement  Slag  Fly ash  Water   SP  Coarse   Fine  SLUMP  FLOW  Strength
0    159.0   0.0      0.0  168.0  6.0   904.0  757.0    0.0  20.0     26.42
1      NaN   NaN      NaN  174.0  NaN     NaN    NaN    NaN   NaN     28.29
2      NaN   NaN      NaN  179.0  NaN     NaN    NaN    NaN   NaN     29.77
3      NaN   NaN      NaN  180.0  NaN     NaN    NaN    NaN   NaN     30.43
4      NaN   NaN      NaN  183.0  NaN     NaN    NaN    NaN   NaN     30.97
5      NaN   NaN      NaN  193.0  NaN     NaN    NaN    NaN   NaN     32.71
6      NaN   NaN      NaN  205.0  NaN     NaN    NaN    NaN   NaN     33.51
7      NaN   NaN      NaN  207.0  NaN     NaN    NaN    NaN   NaN     33.78
8      NaN   NaN      NaN  208.0  NaN     NaN    NaN    NaN   NaN     34.99
9      NaN   NaN      NaN  210.0  NaN     NaN    NaN    NaN   NaN     35.52
10     NaN   NaN      NaN    NaN  NaN     NaN    NaN    NaN   NaN     36.19
11     NaN   NaN      NaN    NaN  NaN     NaN    NaN    NaN   NaN     37.39
12     NaN   NaN      NaN    NaN  NaN     NaN    NaN    NaN   NaN     38.46
13     NaN   NaN      NaN    NaN  NaN     NaN    NaN    NaN   NaN     41.01
14     NaN   NaN      NaN    NaN  NaN     NaN    NaN    NaN   NaN     41.14
15     NaN   NaN      NaN    NaN  NaN     NaN    NaN    NaN   NaN     41.27
16     NaN   NaN      NaN    NaN  NaN     NaN    NaN    NaN   NaN     41.81
17     NaN   NaN      NaN    NaN  NaN     NaN    NaN    NaN   NaN     42.08
18     NaN   NaN      NaN    NaN  NaN     NaN    NaN    NaN   NaN     44.08
19     NaN   NaN      NaN    NaN  NaN     NaN    NaN    NaN   NaN     52.65

In [60]:
slump_data.cov()

,Cement,Slag,Fly ash,Water,SP,Coarse,Fine,SLUMP,FLOW,Strength
Cement,6221.617417,-1161.508095,-3278.051679,352.411380,-23.559374,-2160.342969,284.580813,100.714991,258.390259,275.572938
Slag,-1161.508095,3655.576463,-1666.164124,-32.713593,52.028211,-1196.005958,-702.843499,-150.280333,-347.591678,-157.142937
Fly ash,-3278.051679,-1666.164124,7296.248315,-416.553646,-34.415193,1303.319236,-1530.400660,-88.667135,-83.172706,297.532714
Water,352.411380,-32.713593,-416.553646,408.369650,-8.819791,-1075.668338,146.679569,82.507208,224.387600,-40.269862
SP,-23.559374,52.028211,-34.415193,-8.819791,7.882223,-25.848357,10.366079,-5.230628,-8.696606,-0.833388
Coarse,-2160.342969,-1196.005958,1303.319236,-1075.668338,-25.848357,7813.038363,-2735.267542,-145.539394,-505.918691,-111.327013
Fine,284.580813,-702.843499,-1530.400660,146.679569,10.366079,-2735.267542,4012.223800,112.118880,211.849555,-76.699948
SLUMP,100.714991,-150.280333,-88.667135,82.507208,-5.230628,-145.539394,112.118880,76.577277,139.309280,-15.320388
FLOW,258.390259,-347.591678,-83.172706,224.387600,-8.696606,-505.918691,211.849555,139.309280,308.656061,-17.079700
Strength,275.572938,-157.142937,297.532714,-40.269862,-0.833388,-111.327013,-76.699948,-15.320388,-17.079700,61.437878

In [63]:
slump_data.corr()

,Cement,Slag,Fly ash,Water,SP,Coarse,Fine,SLUMP,FLOW,Strength
Cement,1.000000,-0.243553,-0.486535,0.221091,-0.106387,-0.309857,0.056959,0.145913,0.186461,0.445725
Slag,-0.243553,1.000000,-0.322619,-0.026775,0.306504,-0.223792,-0.183522,-0.284037,-0.327231,-0.331588
Fly ash,-0.486535,-0.322619,1.000000,-0.241321,-0.143508,0.172620,-0.282854,-0.118621,-0.055423,0.444393
Water,0.221091,-0.026775,-0.241321,1.000000,-0.155456,-0.602201,0.114591,0.466568,0.632026,-0.254235
SP,-0.106387,0.306504,-0.143508,-0.155456,1.000000,-0.104159,0.058290,-0.212902,-0.176314,-0.037871
Coarse,-0.309857,-0.223792,0.172620,-0.602201,-0.104159,1.000000,-0.488537,-0.188157,-0.325787,-0.160684
Fine,0.056959,-0.183522,-0.282854,0.114591,0.058290,-0.488537,1.000000,0.202272,0.190370,-0.154484
SLUMP,0.145913,-0.284037,-0.118621,0.466568,-0.212902,-0.188157,0.202272,1.000000,0.906135,-0.223358
FLOW,0.186461,-0.327231,-0.055423,0.632026,-0.176314,-0.325787,0.190370,0.906135,1.000000,-0.124029
Strength,0.445725,-0.331588,0.444393,-0.254235,-0.037871,-0.160684,-0.154484,-0.223358,-0.124029,1.000000

In [65]:
slump_data.skew()

Cement      0.145140
Slag       -0.193079
Fly ash    -0.680019
Water       0.263532
SP          1.125753
Coarse      0.121009
Fine        0.265958
SLUMP      -1.112837
FLOW       -0.520705
Strength    0.192235
dtype: float64

In [68]:
slump_data.isnull().sum()

Cement      0
Slag        0
Fly ash     0
Water       0
SP          0
Coarse      0
Fine        0
SLUMP       0
FLOW        0
Strength    0
dtype: int64

In [69]:
slump_data['FLOW'].mode()

0    20.0
dtype: float64